# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hay Equipos
email: hayequiposr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ahora jugar es mas facil!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://campafutbol.com.ar" # the base hostname & protocol for your site
twitter: hayequipos
Instagram: Hay_equipos

# Build settings
markdown: kramdown
